export const initialFields = {
  "fail-1": {
    checked: false,
    color: "fail",
  },
  "fail-2": {
    checked: false,
    color: "fail",
  },
  "fail-3": {
    checked: false,
    color: "fail",
  },
  "fail-4": {
    checked: false,
    color: "fail",
  },
  "red-2": {
    color: "red",
    value: "2",
    checked: false,
  },
  "red-3": {
    color: "red",
    value: "3",
    checked: false,
  },
  "red-4": {
    color: "red",
    value: "4",
    checked: false,
  },
  "red-5": {
    color: "red",
    value: "5",
    checked: false,
  },
  "red-6": {
    color: "red",
    value: "6",
    checked: false,
  },
  "red-7": {
    color: "red",
    value: "7",
    checked: false,
  },
  "red-8": {
    color: "red",
    value: "8",
    checked: false,
  },
  "red-9": {
    color: "red",
    value: "9",
    checked: false,
  },
  "red-10": {
    color: "red",
    value: "10",
    checked: false,
  },
  "red-11": {
    color: "red",
    value: "11",
    checked: false,
  },
  "red-12": {
    color: "red",
    value: "12",
    checked: false,
  },
  "red-lock": {
    color: "red",
    value: "lock",
    checked: false,
  },
  "yellow-2": {
    color: "darkorange",
    value: "2",
    checked: false,
  },
  "yellow-3": {
    color: "darkorange",
    value: "3",
    checked: false,
  },
  "yellow-4": {
    color: "darkorange",
    value: "4",
    checked: false,
  },
  "yellow-5": {
    color: "darkorange",
    value: "5",
    checked: false,
  },
  "yellow-6": {
    color: "darkorange",
    value: "6",
    checked: false,
  },
  "yellow-7": {
    color: "darkorange",
    value: "7",
    checked: false,
  },
  "yellow-8": {
    color: "darkorange",
    value: "8",
    checked: false,
  },
  "yellow-9": {
    color: "darkorange",
    value: "9",
    checked: false,
  },
  "yellow-10": {
    color: "darkorange",
    value: "10",
    checked: false,
  },
  "yellow-11": {
    color: "darkorange",
    value: "11",
    checked: false,
  },
  "yellow-12": {
    color: "darkorange",
    value: "12",
    checked: false,
  },
  "yellow-lock": {
    color: "darkorange",
    value: "lock",
    checked: false,
  },
  "green-2": {
    color: "green",
    value: "2",
    checked: false,
  },
  "green-3": {
    color: "green",
    value: "3",
    checked: false,
  },
  "green-4": {
    color: "green",
    value: "4",
    checked: false,
  },
  "green-5": {
    color: "green",
    value: "5",
    checked: false,
  },
  "green-6": {
    color: "green",
    value: "6",
    checked: false,
  },
  "green-7": {
    color: "green",
    value: "7",
    checked: false,
  },
  "green-8": {
    color: "green",
    value: "8",
    checked: false,
  },
  "green-9": {
    color: "green",
    value: "9",
    checked: false,
  },
  "green-10": {
    color: "green",
    value: "10",
    checked: false,
  },
  "green-11": {
    color: "green",
    value: "11",
    checked: false,
  },
  "green-12": {
    color: "green",
    value: "12",
    checked: false,
  },
  "green-lock": {
    color: "green",
    value: "lock",
    checked: false,
  },
  "blue-2": {
    color: "blue",
    value: "2",
    checked: false,
  },
  "blue-3": {
    color: "blue",
    value: "3",
    checked: false,
  },
  "blue-4": {
    color: "blue",
    value: "4",
    checked: false,
  },
  "blue-5": {
    color: "blue",
    value: "5",
    checked: false,
  },
  "blue-6": {
    color: "blue",
    value: "6",
    checked: false,
  },
  "blue-7": {
    color: "blue",
    value: "7",
    checked: false,
  },
  "blue-8": {
    color: "blue",
    value: "8",
    checked: false,
  },
  "blue-9": {
    color: "blue",
    value: "9",
    checked: false,
  },
  "blue-10": {
    color: "blue",
    value: "10",
    checked: false,
  },
  "blue-11": {
    color: "blue",
    value: "11",
    checked: false,
  },
  "blue-12": {
    color: "blue",
    value: "12",
    checked: false,
  },
  "blue-lock": {
    color: "blue",
    value: "lock",
    checked: false,
  },
};

export const defaultGameDeck = [
  [
    "red-2",
    "red-3",
    "red-4",
    "red-5",
    "red-6",
    "red-7",
    "red-8",
    "red-9",
    "red-10",
    "red-11",
    "red-12",
    "red-lock",
  ],
  [
    "yellow-2",
    "yellow-3",
    "yellow-4",
    "yellow-5",
    "yellow-6",
    "yellow-7",
    "yellow-8",
    "yellow-9",
    "yellow-10",
    "yellow-11",
    "yellow-12",
    "yellow-lock",
  ],
  [
    "green-12",
    "green-11",
    "green-10",
    "green-9",
    "green-8",
    "green-7",
    "green-6",
    "green-5",
    "green-4",
    "green-3",
    "green-2",
    "green-lock",
  ],
  [
    "blue-12",
    "blue-11",
    "blue-10",
    "blue-9",
    "blue-8",
    "blue-7",
    "blue-6",
    "blue-5",
    "blue-4",
    "blue-3",
    "blue-2",
    "blue-lock",
  ],
];
